// src/app/configure/page.tsx
import { MainNav } from "@/components/main-nav";
import { TagConfigForm } from "@/components/tag-config-form";
import { NxpTagwriterGuide } from "@/components/nxp-tagwriter-guide";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function ConfigurePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <MainNav />
      <main className="flex-1 p-6">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col items-center justify-center space-y-4 text-center py-6">
            <h1 className="text-3xl font-bold tracking-tight">
              Configure NFC Tags
            </h1>
            <p className="max-w-[700px] text-gray-500 dark:text-gray-400">
              Generate parameters for the NXP TagWriter app to program NTAG 424
              DNA tags.
            </p>
          </div>

          <Tabs defaultValue="configure" className="w-full">
            <TabsList className="grid w-full grid-cols-2 mb-6">
              <TabsTrigger value="configure">Configure Tag</TabsTrigger>
              <TabsTrigger value="guide">NXP TagWriter Guide</TabsTrigger>
            </TabsList>

            <TabsContent value="configure">
              <div className="py-6">
                <TagConfigForm />
              </div>
            </TabsContent>

            <TabsContent value="guide">
              <div className="py-6 max-w-3xl mx-auto">
                <div className="bg-white dark:bg-gray-800 p-6 rounded-lg border shadow-sm">
                  <h2 className="text-2xl font-bold mb-4">
                    Using NXP TagWriter
                  </h2>
                  <p className="text-gray-500 dark:text-gray-400 mb-6">
                    Follow this guide to program your NFC tags with the
                    configuration file generated by this tool.
                  </p>

                  <NxpTagwriterGuide />

                  <div className="mt-8 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-100 dark:border-blue-800">
                    <h3 className="font-medium text-blue-800 dark:text-blue-300 mb-2">
                      Additional Resources
                    </h3>
                    <ul className="space-y-2">
                      <li className="flex items-start">
                        <span className="mr-2">•</span>
                        <a
                          href="https://www.nxp.com/docs/en/user-guide/UM11261.pdf"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-blue-600 dark:text-blue-400 hover:underline text-sm"
                        >
                          NXP TagWriter User Manual (PDF)
                        </a>
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2">•</span>
                        <a
                          href="https://www.nxp.com/products/rfid-nfc/nfc-hf/ntag/ntag-for-tags-labels/ntag-424-dna-424-dna-tagtamper-advanced-security-and-privacy-for-trusted-iot-applications:NTAG424DNA"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-blue-600 dark:text-blue-400 hover:underline text-sm"
                        >
                          NTAG 424 DNA Product Information
                        </a>
                      </li>
                      <li className="flex items-start">
                        <span className="mr-2">•</span>
                        <a
                          href="https://www.nxp.com/docs/en/application-note/AN12196.pdf"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-blue-600 dark:text-blue-400 hover:underline text-sm"
                        >
                          Application Notes for SUN Message (PDF)
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  );
}
